Sd-1 Cadastro do Professor na camada de domínio
MIchelJoaquim/apiSchoolite pull request #8
Opened 2023-02-26 14:53 UTC by Mauro301002

Nesta tarefa foi criada a entidade professor, quais possíveis objectos de valor e os possíveis casos de uso.

2023-02-26 15:27 UTC, MIchelJoaquim requested changes
Bom trabalho, vamos melhorar as nomenclaturas!

2023-02-26 15:27 UTC, MIchelJoaquim commented on src/core/entity/subject/acronym.value-object.ts
> +        if(parameters.value.length < 2 )
Evite números mágicos!

o que representa o número 2 ?

2023-02-26 15:27 UTC, MIchelJoaquim commented on src/core/entity/subject/acronym.value-object.ts
> +        if(parameters.value.length > 10)
Evite números mágicos!

o que representa o número 10 ?

use uma constante

2023-02-26 15:27 UTC, MIchelJoaquim commented on src/core/entity/teacher/teacher.ts
> +    private _nivel_academico: Nivel;
Para os nomes das variaveis vamos usar o padrao camelcase
primeira letra minuscula e a inicial de cada palavra em maiuscula 
Ex. 
_nivel_academico - nao
_nivelAcademico - sim

2023-02-26 15:27 UTC, MIchelJoaquim commented on src/core/entity/teacher/teacher.ts
> +    private _area_de_formacao: string;
Para os nomes das variaveis vamos usar o padrao camelcase
primeira letra minuscula e a inicial de cada palavra em maiuscula

2023-02-26 15:27 UTC, MIchelJoaquim commented on src/core/entity/teacher/teacher.ts
> +    private constructor(parameters:{id:Id , nome:Name,nascimento:Date,genero:IGenre,nivel_academico:Nivel, area_de_formacao:string}){
Para os nomes das variaveis vamos usar o padrao camelcase
primeira letra minuscula e a inicial de cada palavra em maiuscula

2023-02-26 15:27 UTC, MIchelJoaquim commented on src/core/entity/teacher/teacher.ts
> +        this._nivel_academico = parameters.nivel_academico;
Para os nomes das variaveis vamos usar o padrao camelcase
primeira letra minuscula e a inicial de cada palavra em maiuscula

2023-02-26 15:27 UTC, MIchelJoaquim commented on src/core/entity/teacher/teacher.ts
> +        this._area_de_formacao = parameters.area_de_formacao;
Para os nomes das variaveis vamos usar o padrao camelcase
primeira letra minuscula e a inicial de cada palavra em maiuscula

2023-02-26 15:27 UTC, MIchelJoaquim commented on src/core/usecase/teacher/cerate.usecase.protocol.ts
> +    }) => Promise <void>;
remover o espaço entre Promise e <

2023-03-01 10:26 UTC, Mauro301002 commented on src/core/entity/subject/acronym.value-object.ts
> +        if(parameters.value.length < 2 )
Vou corrigir já daqui a pouco hahahaha

2023-03-01 15:48 UTC, MIchelJoaquim requested changes

2023-03-01 15:48 UTC, MIchelJoaquim commented on src/core/entity/subject/acronym.value-object.ts
> +        const _maxCharacter = 10;
é uma boa prática colocar constantes como essas fora da classe, em letras maiúsculas

o underline no inicio não é necessário

"dentro das classes usamos o underline para que não haja conflito com os métodos inspetores "

2023-03-01 15:48 UTC, MIchelJoaquim commented on src/core/entity/subject/acronym.value-object.ts
> +            throw new Error("A sigla deve ter pelo menos 2 caracteres");
Ao invés de 2 interpola a constante criada acima

2023-03-01 15:48 UTC, MIchelJoaquim commented on src/core/entity/subject/acronym.value-object.ts
> +            throw new Error("A sigla não deve ter mais de 10 caracteres");
Ao invés de 10 interpola a constante criada acima

2023-03-01 15:48 UTC, MIchelJoaquim commented on src/core/entity/value-object/description.value-object.ts
> +        const words = 3;
O que achas de colocar MIN_WORDS e colocar fora da classe

2023-03-02 10:27 UTC, MIchelJoaquim approved these changes
Bom trabalho!

Parabéns pela sua primeira contribuição.

2023-03-02 10:28 UTC, merged